services:
  welcome-angular-backend:
    container_name: welcome-angular-backend
    build: ./backend
    ports:
      - "5009:5009"
    networks:
      - lan

  welcome-angular-frontend:
    container_name: welcome-angular-frontend
    build: ./frontend
    ports:
      - "5010:5010"
    depends_on:
      - welcome-angular-backend
    networks:
      - lan
